#!/usr/bin/env python3
"""
Copyright (c) 2026 Silicon Laboratories Inc.

SPDX-License-Identifier: Apache-2.0
"""

import argparse
import re
from pathlib import Path

import util.copyright_header

path_prefix = Path("platform/Device/SiliconLabs")
devices = {
    "xg21": "efr32mg21",
    "xg22": "efr32mg22",
    "xg23": "efr32zg23",
    "xg24": "efr32mg24",
    "xg26": "efr32mg26",
    "xg27": "efr32mg27",
    "xg28": "efr32zg28",
    "xg29": "efr32mg29",
    "six301": "simg301",
}


def main():
    parser = argparse.ArgumentParser(
        description="Generate devicetree binding headers for DMA on Series 2 and "
        "Series 3 devices. The headers encode the DMA request source and signals "
        "available on the device."
    )
    parser.add_argument(
        "--out",
        "-o",
        type=Path,
        default=Path(__file__).parent / "out",
        help="Output directory. Defaults to the directory ./out/ relative to the "
        "script. Set to $ZEPHYR_BASE/include/zephyr/dt-bindings/dma/silabs/ to "
        "directly generate output into the expected location within the Zephyr "
        "main tree.",
    )
    parser.add_argument(
        "--sdk",
        "-s",
        type=Path,
        default=Path(__file__).parent.parent / "simplicity_sdk",
        help="Path to Simplicity SDK to extract data from. Defaults to the directory "
        "../simplicity_sdk relative to the script.",
    )
    args = parser.parse_args()

    args.out.mkdir(exist_ok=True)

    for device, source in devices.items():
        path = (
            args.sdk
            / path_prefix
            / source.upper()
            / "Include"
            / f"{source}_ldmaxbar_defines.h"
        )
        data = path.read_text()

        sources = dict(
            map(
                lambda x: (x[0], int(x[1], 16)),
                re.findall(
                    r"^#define _LDMAXBAR(?:0)?_CH_REQSEL_SOURCESEL_([A-Z0-9]+)\s+0x([0-9A-Fa-f]+)UL",
                    data,
                    flags=re.MULTILINE,
                ),
            )
        )

        signals = dict(
            map(
                lambda x: (x[0], int(x[1], 16)),
                re.findall(
                    r"^#define _LDMAXBAR(?:0)?_CH_REQSEL_SIGSEL_([A-Z0-9_]+)\s+0x([0-9A-Fa-f]+)UL",
                    data,
                    flags=re.MULTILINE,
                ),
            )
        )

        max_signal_length = len(max(signals.keys(), key=len))

        include_guard = f"ZEPHYR_INCLUDE_DT_BINDINGS_{device.upper()}_DMA_H_"
        lines = [
            f"#ifndef {include_guard}",
            f"#define {include_guard}",
            "",
            "#include <zephyr/dt-bindings/dt-util.h>",
            '#include "common-dma.h"',
            "",
        ]

        def value(src, sig):
            source = f"FIELD_PREP(DMA_SRC_MASK, {src})"
            signal = f"FIELD_PREP(DMA_SIG_MASK, {sig})"
            return f"({source} | {signal})"

        if "NONE" in sources:
            padding = max_signal_length - len("NONE") + 1
            lines.append(
                f"#define DMA_REQSEL_NONE{' ' * padding}" + value(sources["NONE"], 0)
            )
        for signal_name, signal_value in signals.items():
            for source_name, source_value in sources.items():
                if signal_name.startswith(source_name):
                    padding = max_signal_length - len(signal_name) + 1
                    lines.append(
                        f"#define DMA_REQSEL_{signal_name}{' ' * padding}"
                        + value(source_value, signal_value)
                    )
                    break
            else:
                raise ValueError(f"Invalid source for signal {signal_name}")

        lines += [
            "",
            f"#endif /* {include_guard} */",
            "",
        ]

        description = [
            f"This file was generated by the script {Path(__file__).name} in the hal_silabs module.",
            "Do not manually edit.",
        ]

        outfile = args.out / f"{device}-dma.h"
        header = util.copyright_header.from_path(outfile, description)
        content = header + "\n".join(lines)
        outfile.write_text(content)


if __name__ == "__main__":
    main()
